version: "3.7"
services:
  postgres:
    image: postgres:11
    volumes:
      - type: volume
        source: nodesocial_postgres_data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./databases
        target: /root
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
  db:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_DATABASE: 'maindb'
    ports:
      - 3306:3306
    volumes:
      - nodesocial_mysql_data:/var/lib/mysql
volumes:
  nodesocial_postgres_data:
  nodesocial_mysql_data:
